<h2>Dashboard Admin</h2>

<p><a href="index.php?route=logout">Déconnexion</a></p>

<table border="1" cellpadding="10">
    <tr>
        <th>Nom</th>
        <th>Labels</th>
        <th>Image</th>
        <th>Actions</th>
        <th>Actions</th>
    </tr>
    <?php foreach ($projects as $project): ?>
        <tr>
            <td><?= htmlspecialchars($project->getNom()) ?></td>
            <td><?= htmlspecialchars($project->getLabels()) ?></td>
            <td>
                <?php if ($project->getImg()): ?>
                    <img src="/Portfolio-Pro/public/img/<?= htmlspecialchars($project->getImg()) ?>" width="80" alt="">
                <?php endif; ?>
            </td>
            <td>
                <a href="index.php?route=edit-project&id=<?= $project->getId() ?>" class="btn-edit">
                    Modifier
                </a>

                

            </td>
            <td>
            <a href="index.php?route=delete-project&id=<?= $project->getId() ?>"
        onclick="return confirm('Supprimer ce projet ?')"
        class="btn-delete">
        Supprimer
        </a>
                </td>
        </tr>
    <?php endforeach; ?>
</table>
