<div class="presentation-div">
    <img src="/Portfolio-Pro/public/img/Portrait.jpg" alt="Nolhann Guillaume photo" class='portrait-img'></img>
    <div>
        <h2 class="Bonjour-h2">
            Bonjour, je m'appelle Nolhann Guillaume !
        </h2>
        <p class="presentation-p">
            Je suis actuellement étudiant à 3w Academy en tant que developer web fullstack.
            Je m'intéresse particulièrement au php et j'aime réaliser des projets qui allient backend et design.
            Sur ce portfolio, vous pourrez découvrir mes projets, mes compétences et mes réalisations.
        </p>
    </div>
</div>


<section id="home">rjgkn
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
    </section>
<section id="skills">rjgddddddddddddddkn
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br></section>
<section id="projects">rjssssssssssssssgkn
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br></section>
<section id="contact">rjgsqdqsdqdqskn
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br>
        <br></section>