<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Nolhann GUILLAUME's Portfolio</title>
    <link rel="stylesheet" href="/Portfolio-Pro/public/css/style.css" type="text/css">
    <link rel="shortcut icon" type="image/png" href="img/NG Logo.png">
    <link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-..." crossorigin="anonymous" referrerpolicy="no-referrer"/>

    <script src="/Portfolio-Pro/public/js/script.js" defer></script>
</head>

<body>


    <main class="main-content">
        <?php include "$template.phtml"; ?>
    </main>

    <div class="bulle-nav">
        <a class="bulle-link" data-target="home" data-section="home" title="Accueil">
            <i class="fa-solid fa-house"></i>
        </a>
        <a class="bulle-link" data-target="skills" data-section="skills" title="Mes compétences">
            <i class="fa-solid fa-code"></i>
        </a>
        <a class="bulle-link" data-target="projects" data-section="projects" title="Mes projets">
            <i class="fa-solid fa-folder-open"></i>
        </a>
        <a class="bulle-link" data-target="contact" data-section="contact" title="Me contacter">
            <i class="fa-solid fa-envelope"></i>
        </a>
        <a class="bulle-link" href="/Portfolio-Pro/public/download.php"><i class="fa-solid fa-download"></i></a>
    </div>






    <footer id="footer">
        <p>© 2026 by Nolhann GUILLAUME</p>
    </footer>




</body>
</html>
