<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Révision MVC</title>
    <link rel="stylesheet" href="/Portfolio-Pro/public/css/style.css" type="text/css">
    <link rel="shortcut icon" type="image/png" href="img/revision.png">
    <link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-..." crossorigin="anonymous" referrerpolicy="no-referrer"/>

    <script src="/Portfolio-Pro/public/js/script.js" defer></script>
</head>

<body>

    <main class="main-content">
        <?php include "$template.phtml"; ?>
    </main>

    <div class="bulle-nav">
        <a class="bulle-link" href="#home" data-section="home">
            <i class="fa-solid fa-house"></i>
        </a>
        <a class="bulle-link" href="#skills" data-section="skills">
            <i class="fa-solid fa-code"></i>
        </a>
        <a class="bulle-link" href="#projects" data-section="projects">
            <i class="fa-solid fa-folder-open"></i>
        </a>
        <a class="bulle-link" href="#contact" data-section="contact">
            <i class="fa-solid fa-envelope"></i>
        </a>
        <a class="bulle-link" href="/Portfolio-Pro/public/download.php"><i class="fa-solid fa-download"></i></a>
    </div>





</body>
</html>
